Fix da report generator

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,13 +47,22 @@ jobs:
       - name: 📈 Gerar resumo da cobertura
         working-directory: ./backend
         run: |
-            dotnet tool install --global dotnet-reportgenerator-globaltool
-            export PATH="$PATH:/home/runner/.dotnet/tools"
-            REPORT_FILE=$(find TestResults -name 'coverage.cobertura.xml' | head -n 1)
-            reportgenerator \
-              -reports:"$REPORT_FILE" \
-              -targetdir: TestResults/coverage-report \
-              -reporttypes: TextSummary
+          mkdir -p TestResults/coverage-report
+          dotnet tool install --global dotnet-reportgenerator-globaltool
+          export PATH="$PATH:/home/runner/.dotnet/tools"
+
+          REPORT_FILE=$(find TestResults -name 'coverage.cobertura.xml' | head -n 1)
+          echo "📄 Arquivo de cobertura localizado: $REPORT_FILE"
+
+          if [ -z "$REPORT_FILE" ]; then
+            echo "❌ coverage.cobertura.xml não encontrado. Abortando..."
+            exit 1
+          fi
+
+          reportgenerator \
+            -reports:"$REPORT_FILE" \
+            -targetdir:"TestResults/coverage-report" \
+            -reporttypes:"TextSummary"
 
       - name: 📈 Exibir cobertura no log da pipeline
         working-directory: ./backend
